### ISSUE TITLE
It does not load the image working in ubuntu.

### ISSUE THREAD

**Issue by Byhako** [RSG-Group/hyper-background#3]
It does not load the image working in ubuntu.
![1](https://user-images.githubusercontent.com/19750134/35883861-c958e994-0b56-11e8-8a44-6d8ce2a5d5cc.png)
![2](https://user-images.githubusercontent.com/19750134/35883862-c985349a-0b56-11e8-9900-49e010355420.png)

**Comment by retrixe** [comment]
https://github.com/zeit/hyper/issues/2276 may be related to the 1st error.

Also, you seem to be using hyper-background-image, not hyper-background, which is a different plugin. That plugin is different from hyper-background since it uses a slideshow (a feature I wish to add to this plugin as well) and not a single background.

You can gain assistance for that plugin here, though I cannot guarantee a timely response.
https://github.com/naxyo/hyper-background-image

If you plan to use hyper-background with 2.x canary, please note of #2 which prevents it from working, something being worked on. However, you will be fine if you are on the stable release.
